site_name:        Pawan Bharadwaj
repo_url:         https://github.com/pawbz/pawbz.github.io
site_description: Pawan Bharadwaj 
site_author:      pawbz

theme: yeti
extra_css:
          - assets/Documenter.css

extra_javascript:
          - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
              - assets/mathjaxhelper.js

markdown_extensions:
          - pymdownx.emoji:
                  emoji_generator: !!python/name:pymdownx.emoji.to_svg
          - codehilite
          - extra
          - tables
          - fenced_code


extra_css:
          - assets/Documenter.css


pages:
          - Home: index.md
          - About Me: aboutme.md
          - Publications: publications.md
          - Research: research.md
          - Software: software.md
